In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
# Create a tensor

x = torch.arange(0, 100, 10)

x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
print(f'Minimum: {x.min()}')
print(f'Maximum: {x.max()}')

print(f'Mean: {x.type(torch.float32).mean()}')
print(f'Sum: {x.sum()}')

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [7]:
what_were_covering = {1: "data (prepare and load)",
    2: "build model",
    3: "fitting the model to data (training)",
    4: "making predictions and evaluating a model (inference)",
    5: "saving and loading a model",
    6: "putting it all together"                      
}

In [9]:
# Create *known* parameters
weight = 0.7
bias = 0.3

# Create Data
start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim=1)
y = weight * X + bias

X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

Split Data into Training and Test sets

In [10]:
#    SPLIT         |   Purpose              |  Amount of Total Data    |   How often is it used?
#----------------------------------------------------------------------------------------
# Training Set     | model learns from data |      ~60-80%             |       Always
# Validation Set   |model gets practice test|      ~10-20%             |       Often, but not always
# Testing Set      |model gets evaluated    |      ~10-20%             |       Always

In [13]:
# Create train/test split
train_split = int(0.8 * len(X)) # 80% of dat used for training set
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]

len(X_train), len(y_train), len(X_test), len(y_test)

(40, 40, 10, 10)

In [ ]:
def plot_predictions(train_data=X_train,
                     train_labels=y_train,
                     test_data=X_test,
                     test_labels=y_test,
                     predictions=None):
    """
    Plots training data, test data and compares predictions
    """

    plt.figure(figsize=(10,7))

    # P